sudo: required
services:
    - docker

before_install:
    - docker build -t ravindrapatade/react-test -f ./client/Dockerfile.dev ./

script:
    - docker run -e CI=true ravindrapatade/react-test npm test

after_success:
    - docker build -t ravindrapatade/multi-client ./client
    - docker build -t ravindrapatade/multi-nginx ./nginx
    - docker build -t ravindrapatade/multi-server ./server
    - docker build -t ravindrapatade/multi-worker ./worker
#Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ravindrapatade/multi-client
    - docker ravindrapatade/multi-nginx
    - docker ravindrapatade/multi-server
    - docker ravindrapatade/multi-worker




#Take those images and push them to docker hub

