sudo: required
services:
    - docker

before_install:
    - docker build -t ravindrapatade/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ravindrapatade/react-test npm test

after_success:
    - docker build -t ravindrapatade/multi-client ./client
    - docker build -t ravindrapatade/multi-nginx ./nginx
    - docker build -t ravindrapatade/multi-server ./server
    - docker build -t ravindrapatade/multi-worker ./worker
#Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ravindrapatade/multi-client
    - docker push ravindrapatade/multi-nginx
    - docker push ravindrapatade/multi-server
    - docker push ravindrapatade/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-592580790253"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
